filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/apache2/*.log
output.elasticsearch:
  hosts: ["http://18.181.206.103:9200"]
    # username: "elastic"
    # password: "your-password"

setup.kibana:
  host: "http://18.181.206.103:5601"
  username: "owen"  # 如果 Kibana 有設定密碼，這裡需要加
  password: "123456"
