filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/mariadb/*.log
      - /var/log/php-fpm/*.log
      - /var/log/apache2/*.log
      - /var/log/bitnami/*.log
output.elasticsearch:
  hosts: ["http://13.231.111.185:9200"]
    # username: "elastic"
    # password: "your-password"

setup.kibana:
  host: "http://13.231.111.185:5601"
  username: "owen"  # 如果 Kibana 有設定密碼，這裡需要加
  password: "123456"
